### ISSUE TITLE
Race condition of AttrIndex in indexnode

### ISSUE THREAD

**Issue by amyangfei** [amyangfei/dynamicmq-go#5]
panic sample:

```
panic: runtime error: slice bounds out of range

goroutine 21 [running]:
main.deleteInterval(0xc2080f8310, 0xc209a85770)
    /home/apple/workspace/dynamicmq-go/match/indexnode/stree.go:196 +0x2a1
main.deleteInterval(0xc2080f78f0, 0xc209a85770)
    /home/apple/workspace/dynamicmq-go/match/indexnode/stree.go:199 +0x352
main.deleteInterval(0xc208101810, 0xc209a85770)
    /home/apple/workspace/dynamicmq-go/match/indexnode/stree.go:199 +0x352
main.deleteInterval(0xc2081017a0, 0xc209a85770)
    /home/apple/workspace/dynamicmq-go/match/indexnode/stree.go:199 +0x352
main.(*stree).Delete(0xc208108180, 0xc209a85770)
    /home/apple/workspace/dynamicmq-go/match/indexnode/stree.go:179 +0x35
main.(*AttrIndex).FlushAttrUpdate(0xc208108300)
    /home/apple/workspace/dynamicmq-go/match/indexnode/index.go:213 +0x359
main.ProcessAttrUpdateFlush(0x5547101c, 0xc208196000)
    /home/apple/workspace/dynamicmq-go/match/indexnode/index.go:242 +0x11f
main.func·009()
    /home/apple/workspace/dynamicmq-go/match/indexnode/main.go:206 +0xa8
created by main.AttrUpdateFlushService
    /home/apple/workspace/dynamicmq-go/match/indexnode/main.go:208 +0x25
```

```
fatal error: bad map state

goroutine 27743 [running]:
runtime.gothrow(0x77f7d0, 0xd)
    /usr/local/go/src/runtime/panic.go:503 +0x8e fp=0xc20a900dc8 sp=0xc20a900db0
runtime.evacuate(0x681620, 0xc2080d2000, 0xd)
    /usr/local/go/src/runtime/hashmap.go:799 +0x36a fp=0xc20a900e88 sp=0xc20a900dc8
runtime.growWork(0x681620, 0xc2080d2000, 0x16)
    /usr/local/go/src/runtime/hashmap.go:769 +0x8a fp=0xc20a900ea8 sp=0xc20a900e88
runtime.mapassign1(0x681620, 0xc2080d2000, 0xc20a900fa0, 0xc20a900f78)
    /usr/local/go/src/runtime/hashmap.go:408 +0x18f fp=0xc20a900f48 sp=0xc20a900ea8
main.func·007()
    /home/apple/workspace/dynamicmq-go/match/indexnode/index.go:148 +0x271 fp=0xc20a900fe0 sp=0xc20a900f48
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20a900fe8 sp=0xc20a900fe0
created by main.(*AttrIndex).InsertWaitUpdate
    /home/apple/workspace/dynamicmq-go/match/indexnode/index.go:150 +0xd6
```

**Comment by woshicixide** [comment]
i have same problem with bad map state
